site_name: EVE Knowledge Wiki
site_description: 用 Markdown 编写的知识库 / Wiki
site_url: 
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - search.suggest
    - search.highlight
nav:
  - 首页: index.md
  - 指南:
    - 快速开始: guide/getting-started.md
    - 术语表: guide/terminology.md
    - 新人 FAQ: guide/faq.md
  - PVE 概览: index.md
  - 攻略:
    - PVE 概览: guide/pve-overview.md
    - PVP 概览: guide/pvp-overview.md
  - 工具: tools.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - def_list
plugins:
  - search:
      lang: zh
extra:
  generator: false
